name: CMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        working-directory: ${{ github.workspace }}
        run: |
          if [ ! -d "build" ]; then
            mkdir build
          fi

          if [ ! -d "outputSingle" ]; then
            mkdir outputSingle
          fi

          if [ ! -d "outputParallel" ]; then
            mkdir outputParallel
          fi

          cd build
          cmake ..

          make Lexer

          make clean
          cd ..

      - name: Test script
        working-directory: ${{ github.workspace }}
        run: |
          if [ ! -d "build" ]; then
            mkdir build
          fi

          cd build
          cmake ..

          make run_tests

          make clean
          cd ..
