name: CMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Run script
        working-directory: ${{github.workspace}}
        run: |
          if [ ! -d "build" ]; then
            mkdir build
          fi

          # Output directory
          if [ ! -d "outputSingle" ]; then
            mkdir outputSingle
          fi

          if [ ! -d "outputParallel" ]; then
            mkdir outputParallel
          fi

          # Configure build with cmake
          cd build
          cmake ..

          # Build the program
          make Lexer

          # Clean up the build files
          make clean
          cd ..
